export const categoryTextMap: { [key: string]: { [key: string]: string } } = {
    "Equip": {
        "Shoes": "신발",
        "Overall": "전신",
        "One-Handed Sword": "한손검",
        "One-Handed Blunt Weapon": "한손둔기",
        "Two-Handed Blunt": "두손둔기",
        "One-Handed Axe": "한손도끼",
        "Two-Handed Axe": "두손도끼",
        "Spear": "창",
        "Bow": "활",
        "Crossbow": "석궁",
        "Wand": "완드",
        "Staff": "스태프",
        "Claw": "아대",
        "Hat": "모자",
        "Top": "상의",
        "Bottom": "하의",
        "Earrings": "귀고리",
        "Glove": "장갑",
        "Cape": "망토",
        "Shield": "방패",
    },
    "Use": {
        "Rare Ore": "원석",
        "Potion": "포션",
        "Monster Drop": "몹 드랍",
        "Quest Item": "퀘스트 아이템",
        "Thrown": "투척 무기",
        "Status Cure": "상태 회복",
        "Arrow": "활 전용 화살",
        "Crossbow Bolt": "석궁 전용 화살",
        "Food and Drink": "식음료",
        "Mineral Ore": "원석",
    },
};